### ISSUE TITLE
manage kube proxy parameter defaults and name differs between k8s and k8s::node

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/puppet-k8s#28]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: master branch

## What are you seeing

In `k8s` class:

`Boolean $manage_kube_proxy        = true,`

In `k8s::node` class:

`Boolean $manage_proxy             = false,`

## What behaviour did you expect instead

Should we use the `k8s` `manage_kube_proxy` parameter as default to  `k8s::node` `manage_proxy` parameter?

**Comment by ananace** [comment]
There's actually a huge difference between the two parameters; `k8s::manage_kube_proxy` is used by `k8s::server` (through `k8s::server::resources::manage_kube_proxy`) to deploy kube-proxy as an in-cluster component.  
While `k8s::node::manage_proxy` is used to deploy `kube-proxy` as an on-node component, with entirely different auth and configuration requirements.

Setting both to true would result in a broken cluster, as you'd have two separate proxy instances fighting over routing configuration. Similarly, setting both to false would result in a cluster entirely without the default kube-proxy component - which is used by clusters running network overlays that do their own proxying.
