### ISSUE TITLE
Replace dependency on kubic (or provide other alternative)

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-k8s#77]
[kubic project](https://kubic.opensuse.org/blog/2022-06-10-kubic-retired/) doesn't seem to be officially maintained. 

Would be possible provided at least option for other installation method?

https://github.com/voxpupuli/puppet-k8s/blob/master/manifests/repo.pp#L31

Using `pkgs.k8s.io` would be probably a better choice.

**Comment by ananace** [comment]
There are some differences in what's packaged between the currently community maintained kubic repos and `pkgs.k8s.io`, especially in regards to CRI-O - where there are only 1.28 and 1.29 packages at the moment.  
The CNI packages are also different, and there are likely other quirks in regards to the actual package contents - which I've not looked too deeply into yet.

Still shouldn't be too hard to support, though handling the switchover between kubic->`pkgs.k8s.io` on existing installs might be interesting.

And for the older - but still supported versions - of Kubernetes+CRI-O there'd have to be a fallback as well, to keep using the kubic repos for CRI-O.
